HW5 is completed
efedyakov/go-hw pull request #8
Opened 2023-09-03 15:24 UTC by efedyakov

## Домашнее задание №5 «Параллельное исполнение»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - run.go ~55 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-09-04 02:17 UTC, dshemin requested changes

2023-09-04 02:17 UTC, dshemin commented on hw05_parallel_execution/go.mod
>  require (
Критично:

Не исправлено название модуля.

2023-09-04 02:17 UTC, dshemin commented on hw05_parallel_execution/run.go
> +	for index < n {
Важно:

Проще `for i := 0; i < n; i++ {}`

2023-09-04 02:17 UTC, dshemin commented on hw05_parallel_execution/run.go
> +	if n > len(tasks) {
Важно:

Что будет если n <= 0? Надо обработать и написать тест.

2023-09-04 02:17 UTC, dshemin commented on hw05_parallel_execution/run.go
> +	Message string
Важно:

А для чего Message если мы его не используем?

2023-09-04 02:17 UTC, dshemin commented on hw05_parallel_execution/run.go
> +	for index < len(tasks) {
Важно:

Проще `for _, t := range tasks {}`

2023-09-04 02:17 UTC, dshemin commented on hw05_parallel_execution/run.go
> +		go dosome(tasks[index])
Критично:

Вы не поняли сути задания: надо было запустить n горутин которые бы обслуживали m задач. Т.е. мы реализуем шаблон - воркер пулл.

2023-09-06 11:46 UTC, efedyakov commented on hw05_parallel_execution/go.mod
>  require (
поправил

2023-09-06 11:46 UTC, efedyakov commented on hw05_parallel_execution/run.go
> +	for index < n {
поправил

2023-09-06 11:48 UTC, efedyakov commented on hw05_parallel_execution/run.go
> +	if n > len(tasks) {
Добавил

2023-09-06 11:49 UTC, efedyakov commented on hw05_parallel_execution/run.go
> +	Message string
это я хотел на перспективу использовать, но убрал

2023-09-06 11:50 UTC, efedyakov commented on hw05_parallel_execution/run.go
> +	for index < len(tasks) {
передаелал на  i := n; i < len(tasks); i++
так как перыае таски уже запущены

2023-09-06 11:51 UTC, efedyakov commented on hw05_parallel_execution/run.go
> +		go dosome(tasks[index])
M - это кол-во возмодных ошибок. кол-во задач из len(tasks) определяется ил Ken

2023-09-11 12:15 UTC, merged